# Generated by Django 5.1.3 on 2024-11-30 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='body',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='author_type',
        ),
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asnwer', to='chat.chat'),
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
