# Generated by Django 5.1.3 on 2024-11-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohereIA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentCohereIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentModel', models.CharField(max_length=100)),
                ('currentDataset', models.CharField(max_length=100)),
                ('currentName', models.CharField(max_length=100)),
            ],
        ),
    ]
