# Generated by Django 5.1.3 on 2024-11-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='instalments',
            field=models.IntegerField(default=1),
        ),
    ]
