# Generated by Django 5.1.3 on 2024-11-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_amount_payment_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='issuer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_identification_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paymnet_identification_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
