# Generated by Django 5.1.3 on 2024-11-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
